# Generated by Django 3.0.1 on 2020-01-06 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deckId', models.AutoField(primary_key=True, serialize=False)),
                ('deckName', models.TextField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deck post',
                'verbose_name_plural': 'Deck posts',
            },
        ),
        migrations.CreateModel(
            name='CardTransact',
            fields=[
                ('cardTransactId', models.AutoField(primary_key=True, serialize=False)),
                ('cardId', models.TextField()),
                ('deckId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapp.Deck')),
            ],
            options={
                'verbose_name': 'CardTransact post',
                'verbose_name_plural': 'CardTransact posts',
            },
        ),
    ]
